# Website configuration for Tommy White's portfolio
# Code under <>license, where applicable
# Content under <>license, where applicable

include: ['_pages', '_pages/proj', '_img'] # import page content

timezone: America/NYC
markdown: kramdown
encoding: utf-8

relative_permalinks: false

## SITE SETTINGS
title: TOMMY WHITE
description: >- # this means to ignore newlines until next field
  Hi, I'm Tommy. I like coding in Python, surfing on the coasts, snowboarding/backpacking in
  the mountains, and relaxing in hammocks. 
baseurl: "" # set site subpath to be none (i.e. urls will start at tommy-w.com/)
url: "https://tommy-w.com" # set base hostname with https

author:
  name: Tommy White
  email: "tw@tommy-w.com"

## BUILD SETTINGS
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    twitter: tommywhiteml
    github:  websurfin
    linkedin: tommy-white-5083b3109

# set the order of pages to be included in the header
header_pages:
  - index.md
  - _pages/about.md
  - _pages/projects.md
  # - _pages/faq.md
  - _pages/contact.md

# show excerpts when including blog posts
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
